import { test, expect } from './fixtures/auth'

test.describe('Agendamentos', () => {
  test('deve listar página de agendamentos', async ({ authenticatedPage: page }) => {
    await page.goto('/appointments')
    await expect(page.locator('h1:has-text("Agendamentos")')).toBeVisible({ timeout: 10000 })
    await expect(page.getByRole('button', { name: /novo agendamento/i })).toBeVisible()
  })

  test('deve criar agendamento quando há clientes, pets e serviços', async ({ authenticatedPage: page }) => {
    await page.goto('/appointments')
    await page.waitForLoadState('networkidle')
    await page.getByRole('button', { name: /novo agendamento/i }).click()
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByLabel(/cliente/i)).toBeVisible({ timeout: 5000 })
    const clienteSelect = dialog.locator('.ant-select').first()
    await clienteSelect.click()
    await page.waitForTimeout(300)
    const clienteComPet = page.locator('.ant-select-dropdown .ant-select-item').filter({ hasText: /Pedro|João|Ana|Maria|Carlos/i }).first()
    await expect(clienteComPet).toBeVisible({ timeout: 5000 })
    await clienteComPet.click()
    await page.waitForTimeout(500)
    const petSelect = dialog.locator('.ant-select').nth(1)
    await petSelect.click()
    await page.waitForTimeout(400)
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await page.waitForTimeout(300)
    const serviceSelect = dialog.locator('.ant-select').nth(2)
    await serviceSelect.click()
    await page.waitForTimeout(200)
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await page.waitForTimeout(300)
    const dateInput = dialog.locator('.ant-picker-input input').first()
    await dateInput.fill('25/12/2026')
    await page.keyboard.press('Tab')
    await page.waitForTimeout(200)
    const timeInput = dialog.locator('.ant-picker-input input').nth(1)
    await timeInput.fill('14:00')
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /criar agendamento/i }).click()
    const sucesso = page.getByText(/agendamento criado com sucesso/i)
    const erro = page.locator('.ant-message-error').first()
    await expect(sucesso.or(erro)).toBeVisible({ timeout: 10000 })
    await expect(erro).not.toBeVisible({ timeout: 1000 })
  })
})
